#ifndef ALGO_TREE_ITERATIVE_TRAVERSALS_PREORDER_H_INCLUDED
#define ALGO_TREE_ITERATIVE_TRAVERSALS_PREORDER_H_INCLUDED

#include "tree.h"
#include "array.h"

Array preorder( Tree const * tree );

#endif // ALGO_TREE_ITERATIVE_TRAVERSALS_PREORDER_H_INCLUDED
